server:
  port: ${server_port:9100}
spring:
  profiles:
    active: test
  application:
    name: auth-service

# JTW Config
jwt:
  secret: ${jwt_secret:thisisathirtycharacterlongstring}
  expiration: 3600000
